limit_req_zone $binary_remote_addr zone=general_limit:10m rate=30r/s;
server {
    server_name test.com;
    listen 80;
    location / {
        limit_req zone=general_limit burst=100 nodelay;
        proxy_pass http://juiceshop:3000;
    }
    server_tokens off;
}

